Fix compilation with Debian g++-15_15.2.0-8.
I have no idea why the previous version should be different and breaks
compilation there

```
[ 19%] Building CXX object CMakeFiles/flow_libpolymer.dir/flow/flow_polymer.cpp.o
/usr/bin/c++ -DFMT_SHARED -DHAVE_CONFIG_H=1 -I/<<PKGBUILDDIR>>/obj-loongarch64-linux-gnu -I/<<PKGBUILDDIR>> -I/usr/lib/loongarch64-linux-gnu/openmpi/include -I/usr/lib/loongarch64-linux-gnu/openmpi/include/openmpi -I/usr/include/parmetis -I/usr/include/superlu -I/usr/include/suitesparse -I/usr/include/cjson -I/usr/include/trilinos -I/usr/include/scotch -I/usr/include/metis -I/usr/include/hdf5/openmpi -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -pipe -Wno-dangling-reference -fopenmp -pthread -std=c++17 -MD -MT CMakeFiles/flow_libpolymer.dir/flow/flow_polymer.cpp.o -MF CMakeFiles/flow_libpolymer.dir/flow/flow_polymer.cpp.o.d -o CMakeFiles/flow_libpolymer.dir/flow/flow_polymer.cpp.o -c /<<PKGBUILDDIR>>/flow/flow_polymer.cpp
In file included from /usr/include/dune/istl/paamg/smoother.hh:9,
                 from /<<PKGBUILDDIR>>/opm/simulators/linalg/WellOperators.hpp:33,
                 from /<<PKGBUILDDIR>>/opm/simulators/linalg/ISTLSolver.hpp:47,
                 from /<<PKGBUILDDIR>>/opm/simulators/linalg/ISTLSolverGpuBridge.hpp:25,
                 from /<<PKGBUILDDIR>>/opm/simulators/flow/BlackoilModelNldd.hpp:43,
                 from /<<PKGBUILDDIR>>/opm/simulators/flow/BlackoilModel.hpp:30,
                 from /<<PKGBUILDDIR>>/opm/simulators/flow/SimulatorFullyImplicitBlackoil.hpp:44,
                 from /<<PKGBUILDDIR>>/flow/flow_oilwater_polymer.cpp:25:
/usr/include/dune/istl/paamg/aggregates.hh:1638:26: error: ‘class Dune::Amg::Aggregate<G, S>::VertexSet’ resolves to ‘Dune::Amg::Aggregate<G, S>::VertexSet’, which is not a class type [-Wtemplate-body]
 1638 |     Aggregate<G,S>::size()
      |                          ^
/usr/include/dune/istl/paamg/aggregates.hh:1645:33: error: ‘class Dune::Amg::Aggregate<G, S>::VertexSet’ resolves to ‘Dune::Amg::Aggregate<G, S>::VertexSet’, which is not a class type [-Wtemplate-body]
 1645 |     Aggregate<G,S>::connectSize()
      |                                 ^

```